### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by rEnr3n** [intika/UGChrome#1]
This concerns your binaries repo https://github.com/intika/ungoogled-chromium-binaries/

Can you provide the binaries on github? The links on opendesktop are dynamic making it difficult for package managers to download. https://aur.archlinux.org/packages/ungoogled-chromium-bin/

**Comment by intika** [comment]
Ok no problem i will re upload that on git and let you know over here ;)

**Comment by intika** [comment]
the releases are published on opendesktop.org but for aur i will provide release on my fork...
i just uploaded the last release https://github.com/intika/ungoogled-chromium/releases/download/69.0.3497.100-2/ungoogled-chromium_69.0.3497.100-2_linux.tar.xz i will do so for new versions you can use that git on the future for your aur... 

you can get the md5 on the official binary repo
