### ISSUE TITLE
the releases are published on opendesktop.org but for aur i will provide release on my fork...

### ISSUE THREAD

**Issue by xy2966852232** [intika/UGChrome#4]
the releases are published on opendesktop.org but for aur i will provide release on my fork...
i just uploaded the last release https://github.com/intika/ungoogled-chromium/releases/download/69.0.3497.100-2/ungoogled-chromium_69.0.3497.100-2_linux.tar.xz i will do so for new versions you can use that git on the future for your aur... 

you can get the md5 on the official binary repo

_Originally posted by @intika in https://github.com/intika/UGChrome/issues/1#issuecomment-428674457_

**Comment by intika** [comment]
yes and ? 

*i will provide updated version as soon as i can ;)*
